"""Notion Upload Script.

Reads batch JSON files generated by the stock retrieval scripts and
uploads them to the configured Notion database.

Database: https://www.notion.so/638a8018f09d4e159d6d84536f411441
Data Source: collection://7c5225aa-429b-4580-946e-ba5b1db2ca6d

Note:
    The actual Notion API calls are commented out. Replace the placeholder
    with real notion.create_pages() calls when credentials are configured.
"""

import json
import os
from pathlib import Path

BASE_DATA_DIR = Path(os.getenv("STOCK_APP_DATA_DIR", Path(__file__).resolve().parent / "user-data"))
OUTPUT_DIR = BASE_DATA_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Process each batch file
for batch_num in range(1, 2):
    filename = OUTPUT_DIR / f'notion_batch_{batch_num:04d}.json'

    with open(filename, 'r', encoding='utf-8') as f:
        batch_data = json.load(f)

    print(f"Uploading batch {batch_num}: {len(batch_data['pages'])} pages")

    # Use Notion API to create pages
    # notion.create_pages(
    #     parent={"data_source_id": "7c5225aa-429b-4580-946e-ba5b1db2ca6d"},
    #     pages=batch_data['pages']
    # )
